### ISSUE TITLE
error when "npm run dev"

### ISSUE THREAD

**Issue by Geminika** [alexmarmon/react-mobx-template#1]
Hi Alex,

This is just the boilerplate that I want.
It has all I need, such as react, react-hot, mobx, and mysql.

But, I always get below error after I execute "npm run dev".
I've run it in windows 10, 32 bit.

Any ideas on how to solve it ?
thanks,

 [./src/index.jsx] ./src/index.jsx 577 bytes {1} [built] [1 error]
     + 222 hidden modules
chunk    {2} manifest.dev.js (manifest) 0 bytes [entry] [rendered]

ERROR in ./src/index.jsx

G:\codes\react\boilerplates\react-hot_mobx\react-mobx-template-master\src\index.jsx
  4:17  error  Unable to resolve path to module './app'  import/no-unresolved
  4:17  error  Missing file extension for "./app"        import/extensions

✖ 2 problems (2 errors, 0 warnings)

**Comment by alexmarmon** [comment]
Hello,

Can you do a pull and retry? I had ./app.jsx as ./App.jsx and just changed it.

Let me know if that works for you!
Alex

**Comment by Geminika** [comment]
Yup, it works now.
Somehow I get another issue that I have submit with subject: "Invariant Violation #2"
