### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by EvanGeminika** [alexmarmon/react-mobx-template#2]
hi Alex,

After you fix the first issue.
I manage to execute npm run dev without any error.
But, when I access localhost:3000, I get below error in my browser:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `App`.
invariant
webpack:///./~/fbjs/lib/invariant.js?:44:15
ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent]
webpack:///./~/react-dom/lib/instantiateReactComponent.js?:77:55
ReactCompositeComponentWrapper.performInitialMount
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:367:22
ReactCompositeComponentWrapper.mountComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:258:21
Object.mountComponent
webpack:///./~/react-dom/lib/ReactReconciler.js?:46:35
ReactCompositeComponentWrapper.performInitialMount
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:371:34
ReactCompositeComponentWrapper.performInitialMountWithErrorHandling
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:317:21
ReactCompositeComponentWrapper.mountComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:256:21
Object.mountComponent
webpack:///./~/react-dom/lib/ReactReconciler.js?:46:35
ReactCompositeComponentWrapper.performInitialMount
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:371:34

**Comment by alexmarmon** [comment]
@Geminika Can you pull most recent and update this issue if its still happening? Everything is up to date and working correctly on my mac.
